// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: comment.proto

package server

import (
	"context"

	"comment-system/rpc/comment"
	"comment-system/rpc/internal/logic"
	"comment-system/rpc/internal/svc"
)

type CommentServiceServer struct {
	svcCtx *svc.ServiceContext
	comment.UnimplementedCommentServiceServer
}

func NewCommentServiceServer(svcCtx *svc.ServiceContext) *CommentServiceServer {
	return &CommentServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentServiceServer) CreateComment(ctx context.Context, in *comment.CreateCommentRequest) (*comment.CreateCommentResponse, error) {
	l := logic.NewCreateCommentLogic(ctx, s.svcCtx)
	return l.CreateComment(in)
}

func (s *CommentServiceServer) GetComments(ctx context.Context, in *comment.GetCommentsRequest) (*comment.GetCommentsResponse, error) {
	l := logic.NewGetCommentsLogic(ctx, s.svcCtx)
	return l.GetComments(in)
}

func (s *CommentServiceServer) LikeComment(ctx context.Context, in *comment.LikeCommentRequest) (*comment.LikeCommentResponse, error) {
	l := logic.NewLikeCommentLogic(ctx, s.svcCtx)
	return l.LikeComment(in)
}

func (s *CommentServiceServer) DeleteComment(ctx context.Context, in *comment.DeleteCommentRequest) (*comment.DeleteCommentResponse, error) {
	l := logic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}
