// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Comment struct {
	ID            int64  `json:"id"`
	VideoID       int64  `json:"video_id"`
	UserID        int64  `json:"user_id"`
	Nickname      string `json:"nickname"`
	Avatar        string `json:"avatar"`
	IPLocation    string `json:"ip_location"`
	IsAuthor      bool   `json:"is_author"` // 是否是视频作者
	Content       string `json:"content"`
	ParentID      int64  `json:"parent_id"`
	ReplyToID     int64  `json:"reply_to_id"`   // 回复的目标用户ID
	ReplyToName   string `json:"reply_to_name"` // 回复的目标用户昵称
	RootID        int64  `json:"root_id"`
	LikeCount     int64  `json:"like_count"`
	ReplyCount    int64  `json:"reply_count"`
	IsLiked       bool   `json:"is_liked"`
	IsAuthorLiked bool   `json:"is_author_liked"` // 视频作者是否赞过
	CreatedAt     string `json:"created_at"`      // 格式化后的时间：刚刚、分钟前等
}

type CommentRequest struct {
	VideoID  int64  `json:"video_id"`
	UserID   int64  `json:"user_id"`
	Content  string `json:"content"`
	ParentID int64  `json:"parent_id,optional,default=0"`
}

type CommentResponse struct {
	ID        int64  `json:"id"`
	CreatedAt string `json:"created_at"`
}

type CommentTree struct {
	Comment    Comment        `json:"comment"`
	Replies    []*CommentTree `json:"replies,omitempty"`
	HasMore    bool           `json:"has_more"`    // 是否还有更多子评论
	ReplyTotal int64          `json:"reply_total"` // 子评论总数
	ReplyPage  int64          `json:"reply_page"`  // 当前子评论页码
}

type DeleteCommentRequest struct {
	CommentID int64 `json:"comment_id"`
	UserID    int64 `json:"user_id"`
}

type DeleteCommentResponse struct {
	Success bool `json:"success"`
}

type GetCommentsRequest struct {
	VideoID  int64 `form:"video_id"`
	RootID   int64 `form:"root_id,optional,default=0"` // 0表示查顶级评论，>0表示查该根评论下的子评论
	UserID   int64 `form:"user_id,optional"`           // 用于判断点赞状态
	Page     int64 `form:"page,optional,default=1"`
	PageSize int64 `form:"page_size,optional,default=10"`
}

type GetCommentsResponse struct {
	Comments []*CommentTree `json:"comments"`
	Total    int64          `json:"total"`
}

type LikeCommentRequest struct {
	CommentID int64 `json:"comment_id"`
	UserID    int64 `json:"user_id"`
	Action    int64 `json:"action"`
}

type LikeCommentResponse struct {
	LikeCount int64 `json:"like_count"`
}

type LoginRequest struct {
	UserID int64 `json:"user_id"`
}

type LoginResponse struct {
	Token string `json:"token"`
}
