// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	comment "comment-system/api/internal/handler/comment"
	"comment-system/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取评论列表
				Method:  http.MethodGet,
				Path:    "/comments",
				Handler: comment.GetCommentsHandler(serverCtx),
			},
			{
				// 登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: comment.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 发布评论
				Method:  http.MethodPost,
				Path:    "/comment",
				Handler: comment.CreateCommentHandler(serverCtx),
			},
			{
				// 删除评论
				Method:  http.MethodDelete,
				Path:    "/comment",
				Handler: comment.DeleteCommentHandler(serverCtx),
			},
			{
				// 点赞/取消点赞评论
				Method:  http.MethodPost,
				Path:    "/comment/like",
				Handler: comment.LikeCommentHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
