// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	commentLikeFieldNames          = builder.RawFieldNames(&CommentLike{})
	commentLikeRows                = strings.Join(commentLikeFieldNames, ",")
	commentLikeRowsExpectAutoSet   = strings.Join(stringx.Remove(commentLikeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	commentLikeRowsWithPlaceHolder = strings.Join(stringx.Remove(commentLikeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	commentLikeModel interface {
		Insert(ctx context.Context, data *CommentLike) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CommentLike, error)
		FindOneByCommentIdUserId(ctx context.Context, commentId int64, userId int64) (*CommentLike, error)
		Update(ctx context.Context, data *CommentLike) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCommentLikeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CommentLike struct {
		Id        int64     `db:"id"`
		CommentId int64     `db:"comment_id"` // 评论ID
		UserId    int64     `db:"user_id"`    // 用户ID
		CreatedAt time.Time `db:"created_at"`
	}
)

func newCommentLikeModel(conn sqlx.SqlConn) *defaultCommentLikeModel {
	return &defaultCommentLikeModel{
		conn:  conn,
		table: "`comment_like`",
	}
}

func (m *defaultCommentLikeModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCommentLikeModel) FindOne(ctx context.Context, id int64) (*CommentLike, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", commentLikeRows, m.table)
	var resp CommentLike
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentLikeModel) FindOneByCommentIdUserId(ctx context.Context, commentId int64, userId int64) (*CommentLike, error) {
	var resp CommentLike
	query := fmt.Sprintf("select %s from %s where `comment_id` = ? and `user_id` = ? limit 1", commentLikeRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, commentId, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentLikeModel) Insert(ctx context.Context, data *CommentLike) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, commentLikeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CommentId, data.UserId)
	return ret, err
}

func (m *defaultCommentLikeModel) Update(ctx context.Context, newData *CommentLike) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, commentLikeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.CommentId, newData.UserId, newData.Id)
	return err
}

func (m *defaultCommentLikeModel) tableName() string {
	return m.table
}
