// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: comment.proto

package commentservice

import (
	"context"

	"comment-system/rpc/comment"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Comment               = comment.Comment
	CommentTree           = comment.CommentTree
	CreateCommentRequest  = comment.CreateCommentRequest
	CreateCommentResponse = comment.CreateCommentResponse
	DeleteCommentRequest  = comment.DeleteCommentRequest
	DeleteCommentResponse = comment.DeleteCommentResponse
	GetCommentsRequest    = comment.GetCommentsRequest
	GetCommentsResponse   = comment.GetCommentsResponse
	LikeCommentRequest    = comment.LikeCommentRequest
	LikeCommentResponse   = comment.LikeCommentResponse

	CommentService interface {
		CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error)
		GetComments(ctx context.Context, in *GetCommentsRequest, opts ...grpc.CallOption) (*GetCommentsResponse, error)
		LikeComment(ctx context.Context, in *LikeCommentRequest, opts ...grpc.CallOption) (*LikeCommentResponse, error)
		DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error)
	}

	defaultCommentService struct {
		cli zrpc.Client
	}
)

func NewCommentService(cli zrpc.Client) CommentService {
	return &defaultCommentService{
		cli: cli,
	}
}

func (m *defaultCommentService) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error) {
	client := comment.NewCommentServiceClient(m.cli.Conn())
	return client.CreateComment(ctx, in, opts...)
}

func (m *defaultCommentService) GetComments(ctx context.Context, in *GetCommentsRequest, opts ...grpc.CallOption) (*GetCommentsResponse, error) {
	client := comment.NewCommentServiceClient(m.cli.Conn())
	return client.GetComments(ctx, in, opts...)
}

func (m *defaultCommentService) LikeComment(ctx context.Context, in *LikeCommentRequest, opts ...grpc.CallOption) (*LikeCommentResponse, error) {
	client := comment.NewCommentServiceClient(m.cli.Conn())
	return client.LikeComment(ctx, in, opts...)
}

func (m *defaultCommentService) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error) {
	client := comment.NewCommentServiceClient(m.cli.Conn())
	return client.DeleteComment(ctx, in, opts...)
}
